In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt


In [2]:
data=pd.read_csv("/content/Coimbra_breast_cancer_dataset.csv")

In [3]:
data.shape

(116, 10)

In [4]:
data.head(5)

Age        BMI  Glucose  Insulin      HOMA   Leptin  Adiponectin  Resistin  \
0   48  23.500000       70    2.707  0.467409   8.8071     9.702400   7.99585   
1   83  20.690495       92    3.115  0.706897   8.8438     5.429285   4.06405   
2   82  23.124670       91    4.498  1.009651  17.9393    22.432040   9.27715   
3   68  21.367521       77    3.226  0.612725   9.8827     7.169560  12.76600   
4   86  21.111111       92    3.549  0.805386   6.6994     4.819240  10.57635   

     MCP.1  Classification  
0  417.114               1  
1  468.786               1  
2  554.697               1  
3  928.220               1  
4  773.920               1

In [5]:
data.isnull().sum()

Age               0
BMI               0
Glucose           0
Insulin           0
HOMA              0
Leptin            0
Adiponectin       0
Resistin          0
MCP.1             0
Classification    0
dtype: int64

In [6]:
data.duplicated().sum()

0

In [7]:
data["Age"].unique()
data["BMI"].unique()
data["Glucose"].unique()
data["Insulin"].unique()
data["HOMA"].unique()
data["Leptin"].unique()
data["Adiponectin"].unique()
data["Resistin"].unique()
data["MCP.1"].unique()




array([ 417.114,  468.786,  554.697,  928.22 ,  773.92 ,  530.41 ,
       1256.083,  280.694,  136.855,  318.302,  354.6  ,  174.8  ,
        313.73 ,  632.22 ,  165.02 ,   63.61 ,  191.72 ,  444.395,
        252.449,  588.46 ,  534.224,  572.783,  904.981,  733.797,
       1227.91 ,  586.173,  887.16 , 1102.11 ,  667.928,  581.313,
        864.968,  695.754,  358.624,  960.246,  473.859,  585.307,
        634.602,  263.499,  378.996,  618.272,  698.789,  377.227,
        335.393,  270.142,  200.976,  225.88 ,  206.802,  209.749,
        215.769,  232.006,   45.843,  488.829,  552.444,  382.955,
        573.63 ,  481.949,  321.919,  448.799,   90.6  ,  703.973,
        199.055,  713.239,  737.672,  359.232,  355.31 ,  518.586,
        635.049,  395.976,  301.21 ,  220.66 ,  193.87 ,  244.75 ,
        513.66 ,  195.94 ,  312.   ,  806.724,  483.377,  775.322,
       1698.44 ,  783.796,  910.489,  426.175,  738.034,  799.898,
       1041.843, 1078.359,  923.886,  638.261,  994.316,  764.

In [8]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 116 entries, 0 to 115
Data columns (total 10 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   Age             116 non-null    int64  
 1   BMI             116 non-null    float64
 2   Glucose         116 non-null    int64  
 3   Insulin         116 non-null    float64
 4   HOMA            116 non-null    float64
 5   Leptin          116 non-null    float64
 6   Adiponectin     116 non-null    float64
 7   Resistin        116 non-null    float64
 8   MCP.1           116 non-null    float64
 9   Classification  116 non-null    int64  
dtypes: float64(7), int64(3)
memory usage: 9.2 KB


In [9]:
data.describe()

Age         BMI     Glucose     Insulin        HOMA      Leptin  \
count  116.000000  116.000000  116.000000  116.000000  116.000000  116.000000   
mean    57.301724   27.582111   97.793103   10.012086    2.694988   26.615080   
std     16.112766    5.020136   22.525162   10.067768    3.642043   19.183294   
min     24.000000   18.370000   60.000000    2.432000    0.467409    4.311000   
25%     45.000000   22.973205   85.750000    4.359250    0.917966   12.313675   
50%     56.000000   27.662416   92.000000    5.924500    1.380939   20.271000   
75%     71.000000   31.241442  102.000000   11.189250    2.857787   37.378300   
max     89.000000   38.578759  201.000000   58.460000   25.050342   90.280000   

       Adiponectin    Resistin        MCP.1  Classification  
count   116.000000  116.000000   116.000000      116.000000  
mean     10.180874   14.725966   534.647000        1.551724  
std       6.843341   12.390646   345.912663        0.499475  
min       1.656020    3.210000    45.843000        1.000000  
25%       5.474283    6.881763   269.978250        1.000000  
50%       8.352692   10.827740   471.322500        2.000000  
75%      11.815970   17.755207   700.085000        2.000000  
max      38.040000   82.100000  1698.440000        2.000000

In [10]:
plt.figure(figsize=(10,6))
plt.scatter(data[:,0],data[:,1],c=y,cmap='winter',s=100)

InvalidIndexError: (slice(None, None, None), 0)

<Figure size 1000x600 with 0 Axes>

In [ ]:
sns.pairplot(data)

In [ ]:
data.corr()

In [11]:
x=data.iloc[:,: -1]
y=data.iloc[:,-1]

In [12]:
x

Age        BMI  Glucose  Insulin      HOMA   Leptin  Adiponectin  \
0     48  23.500000       70    2.707  0.467409   8.8071     9.702400   
1     83  20.690495       92    3.115  0.706897   8.8438     5.429285   
2     82  23.124670       91    4.498  1.009651  17.9393    22.432040   
3     68  21.367521       77    3.226  0.612725   9.8827     7.169560   
4     86  21.111111       92    3.549  0.805386   6.6994     4.819240   
..   ...        ...      ...      ...       ...      ...          ...   
111   45  26.850000       92    3.330  0.755688  54.6800    12.100000   
112   62  26.840000      100    4.530  1.117400  12.4500    21.420000   
113   65  32.050000       97    5.730  1.370998  61.4800    22.540000   
114   72  25.590000       82    2.820  0.570392  24.9600    33.750000   
115   86  27.180000      138   19.910  6.777364  90.2800    14.110000   

     Resistin    MCP.1  
0     7.99585  417.114  
1     4.06405  468.786  
2     9.27715  554.697  
3    12.76600  928.220  
4    10.57635  773.920  
..        ...      ...  
111  10.96000  268.230  
112   7.32000  330.160  
113  10.33000  314.050  
114   3.27000  392.460  
115   4.35000   90.090  

[116 rows x 9 columns]

In [13]:
y

0      1
1      1
2      1
3      1
4      1
      ..
111    2
112    2
113    2
114    2
115    2
Name: Classification, Length: 116, dtype: int64

for checking whether output have imbalance data or not

In [14]:
y.value_counts()

Classification
2    64
1    52
Name: count, dtype: int64

In [15]:
from sklearn.model_selection import train_test_split


In [16]:
X_train,X_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=20)

In [17]:
from sklearn.preprocessing import StandardScaler

In [18]:
scaler= StandardScaler()
X_train=scaler.fit_transform(X_train)
X_test=scaler.fit_transform(X_test)

In [19]:
X_train

array([[-1.95124608e+00, -9.55207683e-01, -7.34715292e-01,
        -5.76553943e-01, -4.96175341e-01, -3.46159668e-01,
         1.93420546e+00, -8.44304776e-01, -6.51229351e-01],
       [-5.16625961e-01, -8.27626286e-01, -1.28838470e+00,
        -7.08187660e-01, -5.88818745e-01, -9.45418620e-01,
        -7.00763826e-02, -5.74704784e-01, -3.38068300e-01],
       [ 2.31871494e-01, -2.59631496e-01,  2.34206172e-01,
        -4.76805472e-01, -3.73086428e-01, -1.48010830e-01,
        -1.14745464e+00,  5.82450650e-01, -4.53531746e-01],
       [-1.32749820e+00,  5.23304547e-01, -6.42437057e-01,
        -5.49332509e-01, -4.75725083e-01,  6.19590739e-01,
        -1.63953015e-01,  2.22168354e-01,  6.21197942e-01],
       [-7.03750325e-01, -1.47350711e+00, -2.73324119e-01,
        -6.38420838e-01, -5.08177263e-01, -1.00497445e+00,
         9.29739920e-01, -5.89417447e-01, -1.01429795e+00],
       [-7.03750325e-01, -1.59817409e-01, -2.73324119e-01,
        -6.48890620e-01, -5.14603689e-01,  1.415655

In [20]:
X_test.shape

(24, 9)

In [21]:
from sklearn.linear_model import LogisticRegression
lg= LogisticRegression("l2")


In [22]:
lg.fit(X_train,y_train)

LogisticRegression()

In [23]:
pred=lg.predict(X_test)
print(pred)

[2 2 2 1 1 2 2 1 2 2 1 1 1 2 1 2 1 2 2 1 2 2 2 2]


In [24]:
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix
x= accuracy_score(y_test,pred)
print(x)

0.75


In [25]:
y=classification_report(y_test,pred)
print(y)

              precision    recall  f1-score   support

           1       0.67      0.67      0.67         9
           2       0.80      0.80      0.80        15

    accuracy                           0.75        24
   macro avg       0.73      0.73      0.73        24
weighted avg       0.75      0.75      0.75        24



In [26]:
z= confusion_matrix(y_test,pred)
print(z)

[[ 6  3]
 [ 3 12]]


In [27]:
from sklearn.preprocessing import PolynomialFeatures
poly = PolynomialFeatures(degree=5,include_bias=False)
X_trf = poly.fit_transform(X_train)
print(X_trf.shape)

(92, 2001)


In [28]:
from sklearn.model_selection import cross_val_score
cvs=cross_val_score(lg,X_train,y_train,cv=7,scoring="roc_auc")

In [29]:
clf1 = LogisticRegression()
np.mean(cross_val_score(lg,X_trf,y_train,scoring='accuracy',cv=10))

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _c

0.7477777777777779

In [30]:
print(cvs)

[0.89795918 0.71428571 0.61904762 1.         1.         0.61904762
 0.76190476]


In [31]:
np.mean(cvs)

0.8017492711370263

In [32]:
from sklearn.model_selection import cross_val_predict

In [33]:
v=cross_val_predict(lg,X_train,y_train,cv=5)

In [34]:
print(v)

[1 1 2 1 2 1 2 2 1 1 1 2 1 2 2 2 2 1 2 1 2 2 2 1 2 2 2 1 2 2 2 1 2 2 2 2 1
 2 1 1 1 2 1 2 2 1 1 1 2 2 1 1 2 1 2 2 1 1 2 2 2 1 2 1 1 1 1 2 2 1 2 2 2 2
 2 1 1 1 1 2 1 2 2 2 1 1 1 1 1 2 2 2]


In [35]:
data.describe()

Age         BMI     Glucose     Insulin        HOMA      Leptin  \
count  116.000000  116.000000  116.000000  116.000000  116.000000  116.000000   
mean    57.301724   27.582111   97.793103   10.012086    2.694988   26.615080   
std     16.112766    5.020136   22.525162   10.067768    3.642043   19.183294   
min     24.000000   18.370000   60.000000    2.432000    0.467409    4.311000   
25%     45.000000   22.973205   85.750000    4.359250    0.917966   12.313675   
50%     56.000000   27.662416   92.000000    5.924500    1.380939   20.271000   
75%     71.000000   31.241442  102.000000   11.189250    2.857787   37.378300   
max     89.000000   38.578759  201.000000   58.460000   25.050342   90.280000   

       Adiponectin    Resistin        MCP.1  Classification  
count   116.000000  116.000000   116.000000      116.000000  
mean     10.180874   14.725966   534.647000        1.551724  
std       6.843341   12.390646   345.912663        0.499475  
min       1.656020    3.210000    45.843000        1.000000  
25%       5.474283    6.881763   269.978250        1.000000  
50%       8.352692   10.827740   471.322500        2.000000  
75%      11.815970   17.755207   700.085000        2.000000  
max      38.040000   82.100000  1698.440000        2.000000

In [ ]:
age = int(input("Enter Age(24-89): "))
bmi = int(input("Enter bmi(18-38): "))
glu=int(input("Enter glucose level(60-201): "))
insu=int(input("Enter insulin(2-58): "))
homa=int(input("Enter HOMA(0.4-25): "))
lep=int(input("Enter leptin(4-90): "))
adi=int(input("Enter adiponectin(1.6-38): "))
res=int(input("Enter resistin(3.21-82): "))
mcp=int(input("Enter MCP.1(45-1698): "))

newCust = [[age,bmi,glu,insu,homa,lep,adi,res,mcp]]
result = lg.predict(scaler.transform(newCust))
print(result)
if result == 1:
  print("healthy")
else:
  print("Cancer detected")

"""### *Prediction for all Test Data*"""

y_pred = lg.predict(X_test)
print(y_pred)

1: Healthy controls
2: Patients with breast cancer